PUT http://localhost:3001/api/users/626254d973c637f753ac4a2c
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNyZWF0ZWRieVJFU1RjbGllbnQiLCJpZCI6IjYyNjNjNTE2ZjQyZmI1Njc1MDE3MTA2ZSIsImlhdCI6MTY1MDcwNTczM30.Qqs34fuWpkZ_BMgp3zczFNXxgTvLJHag8HSZjPaGQKk

{
    "username": "createdbyRESTclient",
    "name": "Rest Client",
    "password": "rest-client-password",
    "items": [
        {
            "_id": "62565ba91deb9560fccc3ac8",
            "latin": "Scleroderma citrinum",
            "common": ["Common earthball"],
            "__v": 0
        }
    ]
}
